[project]
name = "mySC"
version = "0.1.0"
requires-python = ">=3.10"
[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"
[tool.setuptools.packages.find]
where = ["."]
include = ["mySC*"]
exclude = ["vendor*"]
